spring.application.name=url_shortener_service

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener_db
spring.datasource.username=postgres
spring.datasource.password=123456789

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.port=8081