spring.application.name=student_management_system

spring.datasource.url=jdbc:postgresql://localhost:5432/smsdb
spring.datasource.username=postgres
spring.datasource.password=123456789

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.cache.type=simple

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always